### ISSUE TITLE
Add v4 to typings?

### ISSUE THREAD

**Issue by mikestecker** [TryGhost/SDK#378]
Can you add v4 to the typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tryghost__content-api/index.d.ts

**Comment by ludo237** [comment]
The types in that repository are really outdated, the SDK should be typescript first at this point

**Comment by ErisDS** [comment]
Types are provided by the community, therefore if you need them to be updated you would need to submit a PR to do that 🙂

**Comment by ErisDS** [comment]
Going to close this as this is managed by the community in a different repo, and so there's nothing to do here.
