### ISSUE TITLE
Refuse to set unsafe header User-Agent 

### ISSUE THREAD

**Issue by tifosiblack** [TryGhost/SDK#426]
Hello everyone,

### Issue Summary
I get an error since I upgraded to the last 1.9.4 version, in Chrome browser.
In the xhr.js I get an exception due to the commit https://github.com/TryGhost/SDK/commit/ae39516130bfa620d03299c1ab869e6cd97c6c99

I guess a fix would be to set this header only in NodeJs context.

Here's the stacktrace
```
Refused to set unsafe header "User-Agent"
setRequestHeader	@	xhr.js?0954:162
forEach	@	utils.js?9908:292
dispatchXhrRequest	@	xhr.js?0954:156
xhrAdapter	@	xhr.js?0954:16
dispatchRequest	@	dispatchRequest.js?5691:58
request	@	Axios.js?aac8:109
Axios.<computed>	@	Axios.js?aac8:131
wrap	@	bind.js?4074:9
defaultMakeRequest	@	content-api.js?2f19:35
makeApiRequest	@	content-api.js?2f19:163
browse	@	content-api.js?2f19:119
eval	@	VM13487 GhostPostListPage.tsx:26
fetchFn	@	query.js?91ec:298
run	@	retryer.js?c38f:95
eval	@	retryer.js?c38f:149
```

### To Reproduce
You have to use the ghostContentApi inside Chrome Browser.

### Technical details:

* Ghost Version: 1.9.4
* Node Version: ?
* Browser/OS: Chrome 101
* Database: ?

**Comment by Brouilles** [comment]
Same here.

**Comment by naz** [comment]
This one is slightly tricky. Firefox has dropped the `User-Agent` header from the forbidden headers list. Chrome on the other hand still drops it ([source](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)). 

I think the best default behavior here would be following:
1. Do not set User-Agent by default in browser environment
2. Set it to default if `userAgent: true` parameter is passed
3. Set it to whatever value is passed in `userAgent` parameter if it's not boolean

This way the defaults will be slightly smarter and if anyone really need it in the browser environment like Firefox can still set it.

**Comment by naz** [comment]
The above behavior would also play nicely with https://github.com/TryGhost/Toolbox/issues/301 allowing to set custom `User-Agent` headers
