### ISSUE TITLE
[ghost admin] Build failure when using @tryghost/admin-api

### ISSUE THREAD

**Issue by Isaac-Tait** [TryGhost/SDK#435]
### Issue Summary

I am working on implementing the admin-api into my NextJS app so that users can access the "paid members" content. Right now I have a bare bones implementation but when I try to build it I get an error that a module [is] not found: Can't resolve 'fs' in @tryghost node modules...

### Steps to Reproduce

1. Install tryghost/admin-api
2.  Implement the api with `url`, `key`, and `version`
3. Run `yarn build`

### Ghost Version

5.1.1

### Node.js Version

18.1.0

### How did you install Ghost?

I am using Ghost(Pro) and NextJS

### Database type

Other

### Relevant log / error output

```shell
Failed to compile.

./node_modules/@tryghost/admin-api/lib/admin-api.js
Module not found: Can't resolve 'fs' in '/Users/isaactait/Desktop/Web_Dev/<my_app>/node_modules/@tryghost/admin-api/lib'

Import trace for requested module:
./node_modules/@tryghost/admin-api/index.js
./lib/ghost.js
./pages/sign-in.js


> Build failed because of webpack errors
```

`./lib/ghost.js`

```
import GhostAdminAPI from '@tryghost/admin-api';

const admin = new GhostAdminAPI({
  url: 'myUrl',
  key: process.env.GHOST_ADMIN_API_KEY,
  version: 'v5.1.1',
});

export function addMember(email, name) {
  return admin.members.add(
    { email, name },
    { send_email: true, email_type: 'signin' }
  );
}
```

`./pages/sign-in`

```
import { addMember } from '../lib/ghost';

const SignIn = () => {
  return (
    <div>
      <form>
        <label htmlFor="name">Full Name</label>
        <input type="text" id="name" name="name" />
        <label htmlFor="email">Email</label>
        <input type="text" id="email" name="email" />
        <button type="submit" onSubmit={addMember}>
          Submit
        </button>
      </form>
    </div>
  );
};

export default SignIn;
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@Isaac-Tait Would you be able to further explain your use-case here?

The Admin-API library is really only intended to be used in a backend, otherwise you need to pass your Admin API key to the frontend. This is a security issue, especially when it has access to a lot of read-write endpoints.

In contrast, `@tryghost/content-api` can be run on the frontend because the Content API key is read-only and only has access to endpoints that are usually public info anyway. That's why `@tryghost/content-api` has a `rollup` config to polyfill `fs`.

**Comment by Isaac-Tait** [comment]
@daniellockyer My goal is to use Admin-API library to build a sign-in/sign-up option for users so that they can access my premium content. Something like this https://www.jakewiesler.com/blog/ghost-jamstack-memberships

**Comment by ErisDS** [comment]
The Admin API is designed for administering your site. The API key for the admin should never be exposed to the browser.

There's a separate API, the members API, which allows members to sign in and sign up. There's no SDK for that at present, but there is [Portal](https://github.com/TryGhost/Portal) which can be dropped into 3rd party site and give you all the sign in and signup behaviour.

**Comment by Isaac-Tait** [comment]
Thank you @ErisDS I will give the members API a shot. 

To clarify I had not exposed the API key to the browser. Rather I had setup a `.env` for my local environment and added the API key to the Vercel environmental variables for the "deployed" site...

I appreciate the guidance though in regards to the Members API I was not aware of that solution. Cheers.
