### ISSUE TITLE
Unable to request multiple pages

### ISSUE THREAD

**Issue by conwayconstar** [TryGhost/SDK#440]
### Issue Summary

Using the content-api within the posts browse method it has an option to query a page. The parameter uses the type `ArrayOrValue<PageParam>`, which suggests the parameter can be an array. When I try to use pages `[1, 2]` to get the multiple pages, the API throws an error as follows.

```
{
   "message": "Validation error, cannot list posts.",
   "context": "Validation (matches) failed for page undefined.page",
   "type": "ValidationError",
   "details": null,
   "property": null,
    "help": null,
    "code": null,
    "id": "bcbe9f40-127b-11ed-a910-33708944938a",
    "ghostErrorCode": null
}
``` 
Is this intentional and you are unable to query multiple pages or is this a bug?

### To Reproduce

1. send browse query as follows
```
ghost.tags.browse({ limit: 6, page: [1, 2] })
```

I have also tested this on with the get endpoint which throws the same error https://demo.ghost.io/ghost/api/content/posts/?key=22444f78447824223cefc48062&limit=6&page=2,3

### Technical details:

* Ghost Version: 1.11.0
* Node Version: 16.14.0
* Browser/OS: browser
* Database: test db

**Comment by ErisDS** [comment]
That is an error in the types - the API only accepts an integer.

**Comment by ErisDS** [comment]
> The parameter uses the type ArrayOrValue<PageParam>

When you said this, I assumed you must be referring to the typings provided by [this package](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tryghost__content-api), but it clearly says [number](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tryghost__content-api/index.d.ts#L15).

Our own docs don't detail a type, but only give an example of a single number: https://ghost.org/docs/content-api/#page

And the content-api package here doesn't give type indications.

I'm super curious where this "type" info came from, but it definitely not anything in this repo, so I'm going to close this as it's not something we can fix.
