### ISSUE TITLE
Got “Invalid token” in Admin API Token authentication even with the token generated by the Bash (cURL) sample code in Doc. 

### ISSUE THREAD

**Issue by GavinCnod** [TryGhost/SDK#458]
### Issue Summary

Got “Invalid token” in Admin API Token authentication even with the token generated by the Bash (cURL) sample code in Doc. 

### To Reproduce

1. Have a Docker installation of Ghost on my server. with "-e NODE_ENV=development" parameter. the website and the admin pages runs fine.
2. Setting a CUSTOM INTEGRATIONS and got the Admin API Key.
3. Write some code in Java of my own Content Mgt app follow the guide of Docs (not only the Split Key to ID and Secret, but also Decode the Hexdecimal Secret). but when using GET/POST /admin/post/ API got error as follow.
4. Even use the Sample Bash Code on Doc (https://ghost.org/docs/admin-api/#token-authentication) to generate JWT Token, also get the following error.
`{
-"errors": [
-{
"message": "Invalid token",
"context": null,
"type": "BadRequestError",
"details": null,
"property": null,
"help": null,
"code": "INVALID_JWT",
"id": "5c91e460-b27b-11ed-b16a-f7290cb584e9",
"ghostErrorCode": null
}
]
}`

Any other info:
1. I tried the /admin/site/ API, which is a unauthenticated, read-only endpoint, and IT RUNs FINE as excepted.
2. I tried switch Accept-Version from v3.0 to v4.0 to v5.0, but nothing change.
3. I tried rewrite the Token Generation logics and use different Java Library but didnot work.
4. I tried to use the Sample code in Doc, still cannot work.
5. Even tried to generate Token in jwt.io, still cannot work.

### Technical details:

* Ghost Version: 5.34 and installed by Docker in dev ENV
* Node Version: 12.12.9
* Browser/OS: doesnt matter here
* Database: SQL Lite

By the way, when I check the Docker Logs, something here may help:

<img width="788" alt="微信截图_20230222155624" src="https://user-images.githubusercontent.com/24690236/220557922-3c6abbee-c13e-4b9a-aa70-1662767dd824.png">

**Comment by daniellockyer** [comment]
I can't reproduce an issue with the bash code in your link. Using an Admin API token + the exact script returns the posts as expected 🙂
