### ISSUE TITLE
Expose primitives in GhostAdminAPI

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/SDK#48]
In our `@tryghost/admin-api` package we only expose direct methods for calling specific endpoints. The auth, url building, data processing, etc aspects all exist but are hidden as internal implementation details.

We'd like to expose as many primitives as possible for SDK users to build their own implementations around in case the provided all-in-one wrapper is insufficient.

The first real-world use-case that's been identified is when using the package inside of Zapier. Zapier provides its own request library which comes with benefits like logging of all requests for easier external debugging. 

TODO:
- [ ] expose internals as separately usable APIs
  - [ ] authentication
  - [ ] url generation
  - [ ] data processing
- [x] allow the networking side of the all-in-one wrapper be overridden/injected

**Comment by kevinansfield** [comment]
I've run into this bug in `axios` when using `GhostAdminAPI` inside our Zapier app https://github.com/axios/axios/pull/1625. Unfortunately the fix has only been released in a beta that is currently failing tests so it's not something we can upgrade to fix but it does add some more urgency to allowing the request method to over overridden/injected.

**Comment by kirrg001** [comment]
@kevinansfield What is the state of this issue?

**Comment by ErisDS** [comment]
Going to close this as we have some improvements planned, but so far this hasn't really been an issue.
